### ISSUE TITLE
Rework admin configuration interface to allow multi-store

### ISSUE THREAD

**Issue by real34** [occitech/Occitech_ShopyMind#1]
**Goal:** allow configuration to be defined in the standard Magento way using xml configuration file to describe admin fields

* [x] Configuration UI defined in standard XML files
* [x] Settings could be set per store
* [x] The current API credentials check is still needed when saving the configuration
* [ ] If possible, display the extension version on the configuration page

**Comment by real34** [comment]
Notes from an email (in french):

> Lors de la soumission des API KEY, les informations suivante sont envoyés à ShopyMind : 
> * Identifiant API
> * Mot de passe API
> * Langue par défaut de la boutique
> * Devise par default de la boutique
> * URL de la page de contact de la boutique
> * Numéro de téléphone de la boutique
> * Timezone par défaut de la boutique
> * Boolean permettantd e savoir si le multiboutique est actif sur la boutique
> * ID de la boutique (multiboutique)
>
> Toutes les informations transmises doivent se rapporter à la boutique que l'on souhaite connecter.

**Comment by damien-biasotto** [comment]
PR - #20 when merged should close this issue.

**Comment by real34** [comment]
FYI oyu can add a "closes #xxx" to your commit message so the issue is closedautomatically when the branch gets merged in `develop`

**Comment by real34** [comment]
Before closing it, we will have to rework the code to send a correct ID to Shopymind. To be discussed
