### ISSUE TITLE
Improve timezone format support

### ISSUE THREAD

**Issue by real34** [occitech/Occitech_ShopyMind#35]
*Goal:* when filtering on timezones, it must be possible to return users who do not have entered their address (which is a critical ShopyMind feature)

Here is an example of a format that has been overlooked in methods using `$timezone` filters, allowing to return customers who do not have an address (e.g customers who juste created an account and never passed an order):

```
array(
            array('country' => 'US', 'region' => 'AL'),
            array('country' => 'FR'),
            false // <-- this means "return users without address"
        )
```

See the `generateTimezonesWhere()` method for further information.

* [x] add support for this format to `ShopymindClient_Callback::getInactiveClients`
* [x] add support for this format to `ShopymindClient_Callback::getBirthdayClientsSignUp`

**Comment by chadrien** [comment]
`ShopymindClient_Callback::getInactiveClients` returns customers who have not ordered since a given date but who have ordered at least once, so in this particular case we should simply check that giving a `false` country does nothing more or less but do not crash either :smiley:
