### ISSUE TITLE
Bad performances with getInactiveClients, getGoodClientsByAmount and getGoodClientsByNumberOrders

### ISSUE THREAD

**Issue by chadrien** [occitech/Occitech_ShopyMind#42]
Databases having a lot of sales can lead to (really) bad performances with the `getInactiveClients`, `getGoodClientsByAmount` and `getGoodClientsByNumberOrders` methods because of the retrieval of guest orders.

This seems to be caused by the conditions on the `customer_email` field (which is not indexed by the way).

**Comment by damien-biasotto** [comment]
:+1: :
