### ISSUE TITLE
Synchronisation des produits

### ISSUE THREAD

**Issue by real34** [occitech/Occitech_ShopyMind#57]
AFIN DE ??
JE PEUX synchroniser la liste des produits

Implémenter une méthode `\ShopymindClient_Callback::syncProducts()` permettant à Shopymind de récupérer par lot tous les produits d'une boutique pour les synchroniser.

Elle est appelée par Shopymind uniquement.

## Paramètres

* `$id_shop` : id de la boutique dont on doit récupérer les données (multiboutiques).
* `$start` : Indice de début de la requête
* `$limit` : Indice de fin de la requete
* `$lastUpdate` : Date de dernière synchronisation (permet de ne pas tout récupérer)
* `$id_product` (défaut = `false`) : id du produit à récupérer
* `$justCount` : juste compter les résultats.

Implémentation côté Prestashop: dans la requête on remplace WHERE 1 par

```
WHERE ' . ($id_product && is_array($id_product) ? '`id_product` IN
('.implode(',',$id_product).')' : '1'). '
```

## Retour

Renvoie un tableau de données formattées par `\ShopymindClient_Callback::getProduct()`

`array(array("données de getProduct()""));`

**Comment by damien-biasotto** [comment]
Resolved by #76.
