### ISSUE TITLE
Synchronisation des catégories

### ISSUE THREAD

**Issue by real34** [occitech/Occitech_ShopyMind#58]
AFIN DE ??
JE PEUX synchroniser la liste des catégories

Implémenter une méthode `\ShopymindClient_Callback::syncProductsCategories()` permettant à Shopymind de récupérer par lot toute les catégories de produits d'une boutique pour les synchroniser.

Elle est appelée par Shopymind uniquement.

## Paramètres

* `$id_shop` : id de la boutique dont on doit récupérer les données (multiboutiques).
* `$start` : Indice de début de la requête
* `$limit` : Indice de fin de la requete
* `$lastUpdate` : Date de dernière synchronisation (permet de ne pas tout récupérer)
* `$id_category` (défaut = false): id de la / des catégorie(s) à récupérer
* `$justCount` : juste compter les résultats.

Exemple dans Prestashop. Dans la requète on remplace WHERE 1 par:

```
WHERE ' . ($id_category && is_array($id_category) ? '`id_category`
IN ('.implode(',',$id_category).')' : '1'). '
```
## Retour

Renvoie un tableau de données formattées par `\ShopymindClient_Callback::getProductCategory()`

`array(array("données de getProductCategory()"));`

**Comment by damien-biasotto** [comment]
Resolved by #72
